### ISSUE TITLE
大佬有没有openwrt上用的认证脚本

### ISSUE THREAD

**Issue by lbhzy** [peterpei1186861238/Srun3k-Boxies#2]
现在用是[https://github.com/ehaut/autologin-srun3k](url)
但是每过十来个小时就会断，有时边用着就断了

**Comment by P-PPPP** [comment]
没有写，因为我是多拨，所以需要curl具体的网卡，还是不太一样的，openwrt的话我一直用的curl，使用方法参考https://wordpress.peterfile.top/index.php/2020/09/26/%e6%b7%b1%e6%be%9c%e6%a0%a1%e5%9b%ad%e7%bd%91%e6%8a%98%e8%85%be%e6%8c%87%e5%8d%97/

**Comment by P-PPPP** [comment]
断的话考虑几种因素
1.udp心跳包（不太可能）
2.被踢了
3.如果间隔十来个小时断，可能是学校的问题，尝试隔几个小时重新登录一下

**Comment by lbhzy** [comment]
> 没有写，因为我是多拨，所以需要curl具体的网卡，还是不太一样的，openwrt的话我一直用的curl，使用方法参考https://wordpress.peterfile.top/index.php/2020/09/26/%e6%b7%b1%e6%be%9c%e6%a0%a1%e5%9b%ad%e7%bd%91%e6%8a%98%e8%85%be%e6%8c%87%e5%8d%97/

发现新大陆，开整，我也一直想能不能通过虚拟多wan实现多拨，奈何没技术，感谢指路

**Comment by P-PPPP** [comment]
已经实测可行，至少在修改mac和DHCP的请求头之后，可以正常获得ip，并且可以多线合一，只是没有测试单线多拨。
但是损耗略大。理论上我校限速2.5mb/s下载，在双线多拨后只能跑到3.7mb/s左右，三拨稳定在5mb/s。但是上传稳定在1.5mb/s。同时延迟也很大，优化方向是修改多拨策略，将延迟较大的ip归纳到单一线路。
本issue不会关闭，欢迎讨论

**Comment by lbhzy** [comment]
> 已经实测可行，至少在修改mac和DHCP的请求头之后，可以正常获得ip，并且可以多线合一，只是没有测试单线多拨。
> 但是损耗略大。理论上我校限速2.5mb/s下载，在双线多拨后只能跑到3.7mb/s左右，三拨稳定在5mb/s。但是上传稳定在1.5mb/s。同时延迟也很大，优化方向是修改多拨策略，将延迟较大的ip归纳到单一线路。
> 本issue不会关闭，欢迎讨论

折腾了一下午，终于成功了，三个账号叠加，到了59
附测速图
![image](https://user-images.githubusercontent.com/48149261/94994456-4723e700-05ca-11eb-87aa-176de0a1bfc8.png)
我利用的是单线多拨虚拟出的3个wan口，依次认证，
稳定性有待以后测试

**Comment by P-PPPP** [comment]
用自己账号的话当然稳定，白嫖估计经常被踢😋

**Comment by lbhzy** [comment]
> 用自己账号的话当然稳定，白嫖估计经常被踢😋

白嫖可太恶劣了，我用室友的😝

**Comment by lbhzy** [comment]
> 已经实测可行，至少在修改mac和DHCP的请求头之后，可以正常获得ip，并且可以多线合一，只是没有测试单线多拨。
> 但是损耗略大。理论上我校限速2.5mb/s下载，在双线多拨后只能跑到3.7mb/s左右，三拨稳定在5mb/s。但是上传稳定在1.5mb/s。同时延迟也很大，优化方向是修改多拨策略，将延迟较大的ip归纳到单一线路。
> 本issue不会关闭，欢迎讨论

![image](https://user-images.githubusercontent.com/48149261/95053092-85ccb500-0722-11eb-9843-dc77829b36e1.png)
实际下载中可以跑满理论值，六个设备同时使用，打王者延迟也在40~50ms，基本稳定

**Comment by P-PPPP** [comment]
![图片](https://user-images.githubusercontent.com/32994395/95271663-07caf400-0871-11eb-8169-532757e378fc.png)
实测可以跑满，估计是白天用的人太多，选早上测试，很稳定
