### ISSUE TITLE
学长好，使用问题

### ISSUE THREAD

**Issue by smooth456** [peterpei1186861238/Srun3k-Boxies#3]
config中添加了自己的用户名和密码，运行surn.exe无界面出现，但是会登录成功。
热点能分享但是不能上网，
直接运行index.html 可以打开网页，但是不能登录和显示已使用的流量

不知道哪里出了问题，请学长指点下

**Comment by smooth456** [comment]
系统是win10

**Comment by P-PPPP** [comment]
等我回头瞅瞅，：）
curl可以登陆。我等会上传个登陆组合脚本
截图如图
![图片](https://user-images.githubusercontent.com/32994395/95681973-68618480-0c15-11eb-83f1-d7122a42e4c1.png)

**Comment by P-PPPP** [comment]
已更新，欢迎使用

**Comment by smooth456** [comment]
能用了，显示也都正常。只是开热点后其他设备连接还是不能上网。我还是整个路由器吧 ：）

**Comment by P-PPPP** [comment]
可能是Windows自带的热点dns解析问题，尝试使用第三方热点共享软件或者手机挂代理使用第三方dns。

**Comment by P-PPPP** [comment]
另外，建议电脑用网线登陆，避免使用同一网卡同时发送热点和登陆

**Comment by smooth456** [comment]
用了网线和360WiFi已经正常分享使用，谢谢指点
